'(("<c:Goblin Pirates:2>We sssurrender! Honessst, we promise to help you pillage any other cassstles!" . "TODO")
("<c:Goblin Pirates:2>We sssurrender! Honessst, we promise not to pillage any other cassstles!" . "TODO")
("The goblins offer surrender, accept terms?" . "TODO")
("+1 crew, +%@" . "TODO")
("<c:Goblin:18>Gahh! <B:0> You are out of ssspace! <B:0> Nice friendsss will not leave usss! I'll build an ledarr!" . "TODO")
("<c:Goblin:18>Gahh! <B:0> You are out of ssspace! <B:0> Nice humansss will not leave usss! I'll build an ledarr!" . "TODO")
("Place block (1x2):" . "TODO")
("One of the goblins joined your crew!" . "TODO")
("While scanning the goblin fortress' computers, you find some fascinating images of the surface world. You record them on a cartridge..." . "TODO")
("Salvage rights: % blocks." . "TODO")
("Take block: (%/%)" . "TODO")
("This will remove the island's only power source, causing it to become unstable (you won't be able to take any more blocks), are you sure?" . "TODO")
("Place block:" . "TODO")
("Place block: (%/%)" . "TODO")
("Accepted surrender, and acquired % blocks!" . "TODO")
("Unacceptable! (+%@)" . "TODO")
)