'(("The hull gleams brightly in the cold air..." . "El casco reluce en el aire frío...")
("The hull gleams brightly in the cold air. Light rain beads on the hull and rolls off..." . "El casco reluce en el aire frío. Una lluvia ligera se acumula en gotas sobre el casco y resbala...")
("The hull sheds sheets of water as rain falls on its gleaming surface..." . "El casco desprende cortinas de agua mientras la lluvia cae sobre su reluciente superficie...")
("A fine dusting of frost coats the unblemished metal. The hull is cold and quiet..." . "Una fina capa de escarcha cubre el metal impecable. El casco está frío y silencioso...")
("Radioactive particles bombard the hull, ash and dust settle in every crevice..." . "Partículas radiactivas bombardean el casco; ceniza y polvo se asientan en cada grieta...")
("Moonlight catches in the hull's seams, the metal pale and ghostly in the dark." . "La luz de la luna se enreda en las junturas del casco; el metal pálido y fantasmal en la oscuridad.")
("Heat shimmers off the plates. The hull creaks and groans as it expands under the harsh light." . "El calor tiembla sobre las planchas. El casco cruje y gime al dilatarse bajo la luz abrasadora.")
("Scored and dented in places, it's seen its share of fights." . "Rayado y abollado en algunas partes, se nota que ha pasado por unas cuantas peleas.")
("The plating is buckled and scorched, fractured by many impacts..." . "El blindaje está deformado y chamuscado, fracturado por muchos impactos...")
)
