'(("<c:Goblin King:3>This whole island needs to be demolissshed! That'sss right, every sssingle block! Not one block can remain!" . "TODO")
("<c:Goblin:2>Hey King, we've finished wiring the island with explosssivesss!" . "TODO")
("<c:Goblin King:3>Heh. Well, thisss complicatesss thingsss... hahahahaha!" . "TODO")
("Are you sure you want a hint?" . "TODO")
("Hint: Check which blocks are vulnerable to ion cannons. " . "TODO")
("The glossary has a search filter for this..." . "TODO")
("<c:Goblin King:3>NO! WRONG!! " . "TODO")
("The island is sssinking and sssome blocksss remain! " . "TODO")
)