'(("1: Goliath" . "TODO")
("challenges/goliath.lisp")
("2: Goblin Raid" . "TODO")
("challenges/goblin_raid.lisp")
("3: Nemesis" . "TODO")
("challenges/backdoor.lisp")
("4: Masonry" . "TODO")
("challenges/masonry.lisp")
("5: Mycelium!" . "TODO")
("challenges/mycelium.lisp")
("6: Porcupine 1" . "TODO")
("challenges/porcupine1.lisp")
("7: Porcupine 2" . "TODO")
("challenges/porcupine2.lisp")
("8: Highwater" . "TODO")
("challenges/decimator.lisp")
("9: Arc Defense" . "TODO")
("challenges/arcgun_defense.lisp")
("10: Pursuit" . "TODO")
("challenges/beacon.lisp")
("11: Exchange" . "TODO")
("challenges/exchange.lisp")
("12: Demolition" . "TODO")
("challenges/demolition.lisp")
("13: Fire Brigade" . "TODO")
("challenges/fire_brigade.lisp")
)