'(("A heavily armed goblin vessel emerges from the clouds, weapons already charging... <B:0> You recognize the distinctive markings on their hull - these are the same scavengers you robbed earlier! <B:0> They've returned with reinforcements and better equipment, eager for revenge..." . "TODO")
("<c:Scavenger:35>Ssso... we meet again! <B:0> Did you think we'd just forget what you did to usss? <B:0> We've spent hours gathering friendsss and better weaponsss. <B:0> Now, you can pay us back... with interessst!" . "TODO")
("Pay 2800@." . "TODO")
("<c:Scavenger:35>Hah! Sssmart choice! <B:0> You humans learn quickly when your livesss are on the line. <B:0> Keep that lessson in mind next time you think about crossing usss!" . "TODO")
("The scavengers take your payment and retreat into the clouds, cackling with satisfaction..." . "TODO")
("Mock their cowardice." . "TODO")
("<c:Scavenger:35>COWARDICE?! <B:0> We'll show you cowardice, you arrogant fool! <B:0> TEAR THEM APART! Leave nothing but scrap metal floating in the cloudsss!" . "TODO")
("Refuse and fight." . "TODO")
("<c:Scavenger:35>Should have taken the easy way out... <B:0> No more talksss! Attack!" . "TODO")
("The goblin scavengers move into battle formation, weapons charging..." . "TODO")
)