'(("<c:Sylph:46>Ah! A sky-dweller with a… <S:1>harmonic matrix<S:0> …what is your word… ah yes, 'power-core'! <B:0> Fascinating construction, though the harmonic resonance is quite… <S:1>limited<S:0> … limited? <B:0> Your crystal vibrates at such a… <S:1>pedestrian tone<S:0> …forgive me, your language lacks precision.<B:0> Perhaps I could… <S:1>retune<S:0> … retune? Yes, retune your matrix to sing in different frequencies? I have studied many resonance patterns from the ancient archives…" .
   "<c:Sylph:46>¡Ah! Un morador del cielo con una… <S:1>harmonic matrix<S:0> …¿cuál es vuestra palabra… ah sí, 'núcleo de energía'! <B:0> Construcción fascinante, aunque la resonancia armónica es bastante… <S:1>limited<S:0> …¿limitada? <B:0> Vuestro cristal vibra en un tono tan… <S:1>pedestrian<S:0> …perdonadme, vuestro idioma carece de precisión.<B:0> Acaso podría… <S:1>retune<S:0> …¿reafinar? Sí, reafinar vuestra matriz para que cante en diferentes frecuencias. He estudiado muchos patrones de resonancia de los archivos antiguos…")
("<c:Sylph:46>What would you like to do?" . "<c:Sylph:46>¿Qué os gustaría hacer?")
("Tune core frequency." . "Afinar frecuencia del núcleo.")
("Done!" . "¡Listo!")
("<c:Sylph:46>" . "<c:Sylph:46>")
("<c:Sylph:46>Which color?" . "<c:Sylph:46>¿Qué color?")
("Done." . "Listo.")
("Buy tuning crystal." . "Comprar cristal de afinación.")
("<c:Sylph:46>You'd like to buy this tuning equipment? Maybe... <B:0> It'll be a bit pricey, 8000@, but you'll be able to retune your core whenever you want..." . "<c:Sylph:46>¿Os gustaría comprar este equipo de afinación? Quizás... <B:0> Será un poco costoso, 8000@, pero podréis reafinar vuestro núcleo cuando queráis...")
("Buy equipment. (8000@)" . "Comprar equipo. (8000@)")
("place tuning equipment:" . "colocar equipo de afinación:")
("<c:Sylph:46>Unfortunately, you don't seem to have enough to buy it yet..." . "<c:Sylph:46>Lamentablemente, parece que aún no tenéis suficiente para comprarlo...")
("Nevermind." . "No importa.")
)
