'(("<c:Sylph:46>Ah! A sky-dweller with a… <S:1>harmonic matrix<S:0> …what is your word… ah yes, 'power-core'! <B:0> Fascinating construction, though the harmonic resonance is quite… <S:1>limited<S:0> … limited? <B:0> Your crystal vibrates at such a… <S:1>pedestrian tone<S:0> …forgive me, your language lacks precision.<B:0> Perhaps I could… <S:1>retune<S:0> … retune? Yes, retune your matrix to sing in different frequencies? I have studied many resonance patterns from the ancient archives…" . "TODO")
("<c:Sylph:46>What would you like to do?" . "TODO")
("Tune core frequency." . "TODO")
("Done!" . "TODO")
("<c:Sylph:46>" . "TODO")
("<c:Sylph:46>Which color?" . "TODO")
("Done." . "TODO")
("Buy tuning crystal." . "TODO")
("<c:Sylph:46>You'd like to buy this tuning equipment? Maybe... <B:0> It'll be a bit pricey, 8000@, but you'll be able to retune your core whenever you want..." . "TODO")
("Buy equipment. (8000@)" . "TODO")
("place tuning equipment:" . "TODO")
("<c:Sylph:46>Unfortunately, you don't seem to have enough to buy it yet..." . "TODO")
("Nevermind." . "TODO")
)