'(("In the distance, you see an island inhabited by a lone castaway..." . "TODO")
("Days stranded: |||| |||| |||| |||| ||||..." . "TODO")
("<c:Castaway:27>Argh. I'm in a tough spot here. After years of fighting goblins, my crew mutinied and left me stranded here. <B:0> At least they picked an island with food, but I'm getting so fed up with eating coconuts and bananas!" . "TODO")
("He seems harmless, invite him aboard?" . "TODO")
("Sadly, there's no room..." . "TODO")
("<c:Castaway:27>Hold on, don't leave me here! I may not meet anyone else for a long time... I'll help you build an addition onto your castle, then there'll be enough space for me to sleep! Let's see... I've got just enough supplies to build a ladder..." . "TODO")
("Place ladder (1x2):" . "TODO")
("<c:Castaway:27> Thanks for rescuing me! I'll try to help out however I can!" . "TODO")
("The castaway joined your crew!" . "TODO")
)