'(("The castaway joined your crew. Starving, he ate 300@ of your food supplies!" . TODO)
("The castaway joined your crew!" . TODO)
("<c:Castaway:38> Thanks for ressscuing me! I'll try to help out however I can! <B:0> ... <B:0> What? You've been banissshed too? <B:0> Ha! HAHAHA! Sssome sssorry lot of goblinsss we are!" . TODO)
("Place block (1x2):" . TODO)
("<c:Castaway:38>Hold on, don't leave me here! I know your cassstle's full, but I can help make some ssspace!" . TODO)
("<c:Castaway:38> We were given ordersss to raid a human ssship. <B:0> Nothing ssspecial. For sssome reason I hesssitated, and was thrown overboard. <B:0> I can make amendsss, I'll show you, I'm ssstill vicious, I ssswear!" . TODO)
("what happened?" . TODO)
("Not today." . TODO)
("Welcome aboard!" . TODO)
("He seems decent, invite him aboard?" . TODO)
("<c:Castaway:38>Yargh!! About time sssomeone showed up! <B:0> I don't even know how long I've been ssstranded here. I've been kicked out of the goblin horde, how could they do this!?" . TODO)
("Days stranded: |||| |||| |||| |||| ||||..." . TODO)
("In the distance, you see an island inhabited by a lone castaway..." . TODO)
)