'(("A heavily armed marauder fortress approaches. Its captain demands to speak with you." . "TODO")
("<c:goblin:2>Yesss captain!" . "TODO")
("(the transmission was cut)" . "TODO")
("<c:Redbeard:12>Yaargh!! I'm just a simple marauder, trying to earn a decent living here! [via petty extortion, how else?] <B:0> So what's it gonna be? Last chance..." . "TODO")
("Pay 600@." . "TODO")
("Fight back." . "TODO")
("<c:Redbeard:12>Negotiate!? Ha. <d:1000> Hahahah! <d:1000> The only negotiation will be how fast you pay me!" . "TODO")
("<c:Redbeard:12>Aarrrgh!! You're trespassing in my domain. Gimme 600@ or I'll blast your island to bits!" . "TODO")
("Here's 600@…" . "TODO")
("You're bluffing!" . "TODO")
("Let's negotiate!" . "TODO")
("Never!" . "TODO")
("<c:redbeard:12>That's not enough, load the cannons!!!" . "TODO")
("<c:redbeard:12>Heh. I think you made the smart decision." . "TODO")
("<c:redbeard:12>Whaatt!! Load the cannons!!!" . "TODO")
("<c:Redbeard:12>Alright, alright! You've bested me! I yield! <B:0> You've disarmed the great Redbeard without sinking him - not many can claim that. <B:0> Take what you want from my hold, just... leave me vessel intact, aye?" . "TODO")
("Among the scattered coins and looted cargo, you find a battered data cartridge, its label barely legible. <B:0> Redbeard waves dismissively. 'Old stories, mostly lies. Take it if you want.'" . "TODO")
)