'(("A small but heavily fortified island appears on your scanners. Scattered debris floats nearby - twisted metal and charred wood from recent conflicts..." . "TODO")
("Your opponent has locked weapons, prepare for battle!" . "TODO")
("<c:Anvil Annie:44>Broke, eh? Well, Sweet Bertha doesn't work for free! Time to collect your scrap as payment instead!" . "TODO")
("<c:Anvil Annie:44>There we go! See how easy that was? Now get out of my airspace before I change my mind!" . "TODO")
("<c:Anvil Annie:44>I KNEW IT! Only goblin spies would refuse to pay! Time to blast some answers out of you!" . "TODO")
("<c:Anvil Annie:44>...That's a powerful warship you're flying. <B:0> <s:3>. . . . . <s:0> <B:0> Alright. New calculation. <B:0> If you wanted me dead, I'd already BE dead. And if you're hunting what I THINK you're hunting... <B:0> ...maybe I've been watching the wrong skies. <B:0> You gotta let me aboard, we should join up!" . "TODO")
("Welcome aboard!" . "TODO")
("Politely decline." . "TODO")
("<c:Anvil Annie:44>I'm sure we can find some space!" . "TODO")
("Place block (1x2):" . "TODO")
("<c:Anvil Annie:44>Finally aboard! Let me just... <B:0> <s:3>. . . <s:0>" . "TODO")
("<c:Anvil Annie:44>Wait. WAIT. <B:0> Those biosigns... <B:0> GOBLINS!? <B:0> I KNEW IT! This was a trap all along!" . "TODO")
("Anvil Annie has turned hostile!" . "TODO")
("Anvil Annie joined your crew!" . "TODO")
("<c:Anvil Annie:44>Understood, right. Hard to trust anyone, these days..." . "TODO")
("<c:Anvil Annie:44>Your fortifications... That's not goblin salvage work. Human military refit. Maybe even pre-migration hardware. <B:0> 400@. Covert rates. <B:0> And you sail straight through - no loitering, no surveys, no 'equipment malfunctions' near my perimeter!" . "TODO")
("Pay 400@." . "TODO")
("<c:Anvil Annie:44>...HA! Oh, that's PRECIOUS! <B:0> You actually thought - with THAT floating scrapyard - you could intimidate ME? <B:0> 800@ now. And count yourself lucky I don't raise it any higher!" . "TODO")
("Pay 800@." . "TODO")
("Refuse bribe." . "TODO")
("<c:Anvil Annie:44>Alright, let's negotiate. <B:0> I'm listening, but no sudden moves, gotit?" . "TODO")
("Pay 700@." . "TODO")
("Intimidate." . "TODO")
("Intimidate. (risky)" . "TODO")
("Intimidate. (foolish)" . "TODO")
("<c:Anvil Annie:44>Unknown vessel! You're trespassing in MY airspace! <B:0> I've been keeping this stretch of sky clear for twenty years, and I don't plan on stopping now! <B:0> Don't even think about giving me that 'innocent trader' routine - I can smell goblin sympathizers from three leagues away!" . "TODO")
("<c:Anvil Annie:44>Tell you what, spy - <B:0>you hand over 700@ right now, and maybe Sweet Bertha here won't blow a hole in your hull! (pats cannon)" . "TODO")
("Negotiate." . "TODO")
("Refuse Bribe." . "TODO")
("We aren't spies!" . "TODO")
("<c:Anvil Annie:44>Course you'd say that. Real spies always deny it. Innocent traders? They get confused, ask what I'm talking about. But you knew EXACTLY what I meant..." . "TODO")
("What's this debris field?" . "TODO")
("<c:Anvil Annie:44>Spies, saboteurs, sleeper agents! They think they're so clever with their fake distress calls and forged cargo manifests! But I can spot 'em from leagues away! <B:0> See that scorched hull fragment? 'Friendly trader' who tried to scan my weapon configurations! <B:0> The nerve! They're ALL connected, part of some massive intelligence network! <B:0> Anyway..." . "TODO")
)