'(("The station begins charging its weapons!" . TODO)
("Refuse." . TODO)
("Examine the station…" . TODO)
("Pay 600@ toll." . TODO)
("While the old empire is now fragmented and most of its weapons systems are offline, this automated vessel seems to still be functioning. <B:0>The station's computers demand a toll of 600@. Pay?" . TODO)
("Refuse and fight!" . TODO)
("Just pay the toll." . TODO)
("Sabotage it." . TODO)
("Disable the sensors?" . TODO)
("It won't know you passed. But someone will eventually notice the damage…" . TODO)
("Your engineer has a simpler solution: physically disable the station's sensor array. <B:0> " . TODO)
("Whether this toll is even legally enforceable would require months of archival research. <B:0> " . TODO)
("…but that decree was suspended pending review after the empire fractured…" . TODO)
("…which was amended by decree 891 in the Third Solar Cycle… <B:0> " . TODO)
("The toll demand references Imperial Transit Code section 47-G, subsection 12… <B:0> " . TODO)
("Your crew examines the station more closely. <B:0> " . TODO)
("The station deactivates and allows you to pass." . TODO)
("Your crew examines the transmission: a properly formatted Imperial Transit Voucher, complete with authentication seals and tax filing instructions. <B:0> According to the attached guidance, this 600@ toll is fully deductible from your annual merchant levy... <B:0> ...which was last collected seventeen years ago." . TODO)
("After a moment, it transmits a receipt datapacket to your systems." . TODO)
("The station processes your payment. <B:0> " . TODO)
("Insufficient funds! The station begins charging its weapons!" . TODO)
("You slip past the blind station without incident." . TODO)
("The weapons array remains active, but its targeting systems go dark. <B:0> " . TODO)
("Your crew targets the station's external sensors with precision fire. <B:0> " . TODO)
("An ancient imperial missile platform contacts you and demands payment..." . TODO)
)