'(("Your sensors detect some goblin scavengers returning from a raid. <B:0> Their leader excitedly waves you down, eager to trade their mysterious finds..." . "Tus sensores detectan a unos carroñeros goblin que regresan de una incursión. <B:0> Su líder te hace señas emocionado, ansioso por comerciar con sus misteriosos hallazgos...")
("Place first " . "Colocar primer ")
("Place second " . "Colocar segundo ")
("<c:Scavenger:35>Yesss! Sssmart choice! Don't mind the burn marksss, they add character!" . "<c:Carroñero:35>¡Sssí! ¡Decisssión inteligente! ¡No te fijesss en las marcas de quemadura, le dan carácter!")
("<c:Scavenger:35>Gah! Fine, take them! <B:0> Ssstolen from some fat merchantsss anyway... <B:0> But we won't forget thisss. We know where to find more friendsss..." . "<c:Carroñero:35>¡Gah! ¡Vale, llévatelos! <B:0> De todas formasss los robamos de unos comerciantesss gordos... <B:0> Pero no olvidaremosss esto. Sssabemos dónde encontrar más amigosss...")
("The goblins storm off, swearing vengeance..." . "Los goblins se largan furiosos, jurando venganza...")
("<c:Scavenger:35>Heh, we'll ssstick around. Come find usss when you've ssscraped up the resources! <B:0> (or use the START menu to return to the world map)" . "<c:Carroñero:35>Je, nosss quedamosss por aquí. ¡Ven a busscarnosss cuando juntesss losss recursosss! <B:0> (o usa el menú START para volver al mapa)")
("<c:Scavenger:35> Found thessse %s" . "<c:Carroñero:35> Encontré estosss %s")
(" on a human isssle!" . " ¡en una isssla humana!")
("... err ... Well, don't worry where I got them! <B:0>" . "... eeh ... ¡No te preocupesss de dónde los saqué! <B:0>")
(" Still working, barely sssinged! 1300@ for two, yesss? Better price than waiting for your workshop to build them!" . " ¡Todavía funcionan, apenas chamuscadosss! ¿1300@ por los dos, sssí? ¡Mejor precio que esperar a que tu taller los construya!")
("Purchase for 1300@." . "Comprar por 1300@.")
("Take by force." . "Tomar por la fuerza.")
("Decline offer." . "Rechazar oferta.")
("<c:Scavenger:35>Sorry, that's not enough! Do you want to sssalvage some ssstuff to come up with the ressourcesss for payment?" . "<c:Carroñero:35>¡Lo sssiento, esso no basssta! ¿Quieres dessguazar algo para reunir losss recursssosss del pago?")
("<c:Scavenger:35>Ssseems like you have enough now! <B:0> Buy two %s for 1300@?" . "<c:Carroñero:35>¡Parece que ya te alcansssa! <B:0> ¿Comprasss dosss %s por 1300@?")
("<c:Scavenger:35>Sorry, the price wasss 1300@, you're ssstill %@ short…" . "<c:Carroñero:35>Lo sssiento, el precio era 1300@ y todavía te faltan %@…")
("Salvage more stuff…" . "Desguazar más cosas…")
("Exit." . "Salir.")
)
