'(("Your sensors detect some goblin scavengers returning from a raid. <B:0> Their leader excitedly waves you down, eager to trade their mysterious finds..." . "TODO")
("Place first " . "TODO")
("Place second " . "TODO")
("<c:Scavenger:35> Found thessse %s" . "TODO")
(" on a human isssle!" . "TODO")
("... err ... Well, don't worry where I got them! <B:0>" . "TODO")
(" Still working, barely sssinged! 1300@ for two, yesss? Better price than waiting for your workshop to build them!" . "TODO")
("...but you don't ssseem to have enough. Do you want to sssalvage some stuff to come up with the fundsss? I'll check back in 15 secondsss?" . "TODO")
("Purchase for 1300@." . "TODO")
("Take by force." . "TODO")
("<c:Scavenger:35>Gah! Fine, take them! <B:0> Ssstolen from some fat merchantsss anyway... <B:0> But we won't forget thisss. We know where to find more friendsss..." . "TODO")
("The goblins storm off, swearing vengeance..." . "TODO")
("Decline offer." . "TODO")
("<c:Scavenger:35>Ssseems like you have enough now!" . "TODO")
("<c:Scavenger:35>Sorry, that's not enough! Do you want to sssalvage some ssstuff to come up with the ressourcesss for payment? I'll check back in in 15 seconds?" . "TODO")
("<c:Scavenger:35>Yesss! Sssmart choice! Don't mind the burn marksss, they add character!" . "TODO")
)