'(("Some merchants broadcast an advertisement for advanced technology! Let's see if they have anything useful!" . "TODO")
("<c:Merchant:7>We ordered too many %s and we're having a big sale today! Much cheaper than if you built them yourself. @ for two, what do you say?" . "TODO")
("Place first " . "TODO")
("Place second " . "TODO")
("<c:Merchant:7>Looks great! You made a fine choice!" . "TODO")
("<c:Merchant:7>Ok! I'll be here. Come see me again when you're ready! <B:0> (or use the START menu to return to the world map)" . "TODO")
("<c:Merchant:7>Sorry, that's not enough! Do you want to salvage some stuff to come up with the resources for payment?" . "TODO")
("<c:Merchant:7>Looks like you have enough now. <B:0> Buy two %s for %@?" . "TODO")
("<c:Merchant:7>Sorry, the price was %@, you're still %@ short…" . "TODO")
("Salvage more stuff…" . "TODO")
("Exit." . "TODO")
)