'(("A Sylph supply depot appears through the clouds, its crystalline sensors tracking your approach. <B:0> Your radio crackles with a precise, emotionless transmission..." . "TODO")
("<c:Sylph Quartermaster:53>Scanning vessel configuration... <B:0> Analysis: sub-optimal armament for projected threat parameters in your operational zone. <B:0> Conclave logistics has authorized requisition of two % emplacements to your vessel. <B:0> Cost: materials only, %@." . "TODO")
("Accept for %@." . "TODO")
("Refuse allocation." . "TODO")
("<c:Sylph Quartermaster:53>Acknowledged. Tactical assessment indicates 73% probability you will not survive the next three hostile encounters with current armament. <B:0> Your decision is... inefficient. <B:0> Requisition cancelled." . "TODO")
("Install first " . "TODO")
("Install second " . "TODO")
("<c:Sylph Quartermaster:53>Transfer complete. Conclave tactical projections indicate improved survival probability. <B:0> Maintain operational readiness. Quartermaster out." . "TODO")
("<c:Sylph Quartermaster:53>Standing by. Come see me again when you're ready! <B:0> (or use the START menu to return to the world map)" . "TODO")
("<c:Sylph Quartermaster:53>Sorry, that's not enough! Do you want to salvage some stuff to come up with the resources for payment?" . "TODO")
("<c:Sylph Quartermaster:53>Looks like you have enough now. <B:0>Accept two %s for %@?" . "TODO")
("<c:Sylph Quartermaster:53>Sorry, the cost was %@, you're still %@ short…" . "TODO")
("Salvage more stuff…" . "TODO")
("Exit." . "TODO")
)