'(("You discover the wreckage of a goblin raid..." . "TODO")
("Goblins from the surface! Now, they too inhabit the skies... nowhere is safe..." . "TODO")
("The island seems thoroughly ransacked... but the pirates inexplicably left behind a weapon. Haul it aboard?" . "TODO")
("Yeah!" . "TODO")
("No, leave it." . "TODO")
("What's a goblin raid?" . "TODO")
("Looks like goblins from the surface world ransacked this island for scrap metal and fuel. It's unclear why they left a weapon lying around, perhaps they left in a hurry. <B:0> Anyway, pick up the weapon?" . "TODO")
("Pick a slot (%x%)" . "TODO")
("Like a missile-silo, but starts fires! A useful addition!" . "TODO")
("A special cannon that fires projectiles in a wide arc. How useful!" . "TODO")
("Wow, a very powerful weapon! <B:0> You're lucky to have found this..." . "TODO")
("Huh!? Who doesn't want free stuff? Suit yourself..." . "TODO")
)