'(("A distress call sounds over your radio! <B:0> <b:/scripts/data/img/destroyed_town.img.bin>The remnants of a town appear, wrecked by war.." . "TODO")
("<c:Goblin Raider:39>Finally, sssomeone answered! <B:0> My raid crew left me behind when the town's defenssses were stronger than expected. <B:0> Got knocked out by some debris when their ion cannon hit us... By the time I came to, everyone wasss gone. _bitter_laugh_ Guesss they figured I was dead weight. <B:0> Would you have room for a more... reliable crew member?" . "TODO")
("She seems decent, invite her aboard?" . "TODO")
("Welcome aboard!" . "TODO")
("Not today." . "TODO")
("<c:Goblin Raider:39>Hold on, don't leave me here! I know your cassstle's full, but thisss island is burning!" . "TODO")
("Place block (1x2):" . "TODO")
("<c:Goblin Raider:39>Thanks for ressscuing me! I'll try to help out however I can!" . "TODO")
("The goblin joined your crew!" . "TODO")
)