'(("The villager girl joined your crew!" . TODO)
("<c:Girl:14>Wait, you're serious! I guess I asked for it haha..." . TODO)
("Place cargo bay (1x2):" . TODO)
("<c:Girl:14>Wait up a second, I know your castle's pretty full, but don't leave me here! This island is literally burning! I'll even sleep in a cargo bay..." . TODO)
("Sadly, there's no room..." . TODO)
("<c:Girl:14>.<d:500>.<d:500>.<d:500> Actually, I was wondering if you can do me one more small favor? I brought this data cartridge with an old photo of my village, can you hold onto it for me?" . TODO)
("<c:Girl:14>Hmm.. well let's see. I'm good at cooking, I can clean your ship, I'm pretty decent at crochet and... I don't know if this is even relevant, but I'm a blackbelt in karate! <B:0> Can I come along?" . TODO)
("Why let her aboard?" . TODO)
("No." . TODO)
("Sure!" . TODO)
("She seems harmless, invite her aboard?" . TODO)
("<c:Girl:14>Heya! I'm so lucky someone showed up! Damned goblins took my whole village as hostages. Somehow I slept through the whole thing... Anyway, please take me with you! I promise not to get in the way!" . TODO)
("A distress call sounds over your radio! <B:0> <b:/scripts/data/img/destroyed_town.img.bin>The remnants of a town appear, wrecked by war.." . TODO)
)