'(("The Sylph joined your crew!" . TODO)
("<c:Sylph Researcher:49>Thank you. <B:0> <d:600> I keep thinking - if I'd phrased it differently, shown them the calculations in a way they'd understand... <B:0> <d:800> But I presented it like a research paper. To people fighting for survival every day. <B:0> They needed practical help, not observations." . TODO)
("Place block (1x2):" . TODO)
("<c:Sylph Researcher:49>Ah. Full capacity. That's... let me think. <B:0> The structural integrity here is compromised. I can calculate optimal placement for-" . TODO)
("<c:Sylph Researcher:49>We document adaptation strategies - how humans build efficiently, manage with limited resources. <B:0> The Conclave thought understanding survival methods might help our cities. <B:0> <d:800> I told them their defenses were inadequate. They didn't listen. <B:0> Maybe I didn't explain it right. Maybe they thought I was... condescending." . TODO)
("field research?" . TODO)
("Not today." . TODO)
("Welcome aboard!" . TODO)
("He seems shaken, invite him aboard?" . TODO)
("<c:Sylph Researcher:49>Someone's here! Thank the winds. <B:0> I was conducting field research when raiders attacked. I tried to warn the villagers - they thought I was overreacting. 'Sylph paranoia,' one said. <B:0> When the attack came, I tried to help defend, but... <B:0> I'm a researcher, not a soldier. The building collapsed. Everyone scattered or was taken. <B:0> By the time I dug myself out, I was alone." . TODO)
("A distress call sounds over your radio! <B:0> <b:/scripts/data/img/destroyed_town.img.bin>The remnants of a town appear, wrecked by raiders..." . TODO)
)