'(("A small fortress hurtles through the air, with goblins in pursuit. The captain calls for help..." . "Una pequeña fortaleza surca el aire a toda velocidad, con goblins en persecución. El capitán pide ayuda...")
("Place weapon where? (2x2)" . "¿Colocar arma dónde? (2x2)")
("<c:Captain:7> OK, all finished! The weapon recharges quite slowly, but nothing's more destructive! You need to move one of your crew into the weapon, though, or it won't recharge." . "<c:Capitán:7> ¡OK, todo listo! El arma se recarga bastante lento, ¡pero no hay nada más destructivo! Eso sí, necesitas mover a uno de tus tripulantes al arma, o no se recargará.")
("<c:Captain:7>Alright, I'll wait here. Come find me when you've scraped together the resources! <B:0> (or use the START menu to return to the world map)" . "<c:Capitán:7>Muy bien, esperaré aquí. ¡Ven a buscarme cuando hayas reunido los recursos! <B:0> (o usa el menú START para volver al mapa)")
("<c:Captain:7>Look, those goblins are getting closer... <B:0> Tell you what - pay me %@ instead of %@, and help me destroy the evidence that I was ever here. <B:0> They'll assume YOU stole it from them directly. Deal?" . "<c:Capitán:7>Mira, esos goblins se acercan... <B:0> Te propongo algo - págame %@ en vez de %@, y ayúdame a destruir las pruebas de que estuve aquí. <B:0> Asumirán que TÚ se lo robaste directamente. ¿Trato?")
("Hide evidence (%@)." . "Ocultar pruebas (%@).")
("Pay %@…" . "Pagar %@…")
("<c:Captain:7>I managed to steal this decimator from some goblins, but they're catching up to me! I know... I could sell you the weapon! I'll install it on your island for %@..." . "<c:Capitán:7>Logré robar este diezmador a unos goblins, ¡pero me están alcanzando! Ya sé... ¡podría venderte el arma! Te la instalo en tu isla por %@...")
("Here's %@…" . "Aquí tienes %@…")
("Can I have a discount?" . "¿Me haces un descuento?")
("No thanks." . "No, gracias.")
("<c:Captain:7>Sorry, I went to all this trouble, I really can't sell you this tech for less than %@. Do you want to salvage some stuff to come up with the funds?" . "<c:Capitán:7>Lo siento, después de todo lo que pasé, no puedo venderte esta tecnología por menos de %@. ¿Quieres desguazar algo para reunir los fondos?")
("<c:Captain:7>Looks like you've got enough now. <B:0> Install the decimator for %@?" . "<c:Capitán:7>Parece que ya tienes suficiente. <B:0> ¿Instalo el diezmador por %@?")
("<c:Captain:7>Sorry, the price was %@, you're still %@ short…" . "<c:Capitán:7>Lo siento, el precio era %@, aún te faltan %@…")
("Salvage more stuff…" . "Desguazar más cosas…")
("Exit." . "Salir.")
)
