'(("An unusual structure emerges from the clouds... <B:0> A fortress of rough-hewn stone, adorned with crude but intricate carvings. <B:0> Inside, you spot goblin figures moving with unexpected discipline and precision..." . "TODO")
("<c:Goblin Monk:41>We are the Ashwalker Order. While other goblins chase mere plunder, we seek the ancient strength that let our ancestors survive the surface world. <B:0> Our training could serve your crew well... for the right price." . "TODO")
("Recruit? %@" . "TODO")
("No thanks." . "TODO")
("You cannot afford to pay. The monks become impatient, and cut the transmission." . "TODO")
("<c:Goblin Monk:41>This is inconvenient, but I suppose we can help you out..." . "TODO")
("Place block (1x2):" . "TODO")
("<c:Warrior Monk:41>I live to serve!" . "TODO")
("The monk joined your crew!" . "TODO")
("The Ashwalker Monk reluctantly hands over a datacart that he'd been keeping..." . "TODO")
("The monks became angry, and cut the transmission." . "TODO")
)