'(("You come upon the scene of a heated battle. <B:0> A goblin resource harvester vessel is attacking an unarmed village, its beams slicing through the town. <B:0> Noticing you, the goblins briefly stop attacking…" . "TODO")
("<c:Villager:5>We're being raided! That goblin ship over there is slicing chunks off of our town! <B:0> They just let the scrap fall to the ruined world below, where their friends collect the fallen resources. <B:0> I know it's a long shot, but any chance you could help us?" . "TODO")
("<c:Goblin:2> You think you can fight usss?! Hah!!" . "TODO")
("One of the villagers came aboard to help out!" . "TODO")
("<c:Goblin:2> HAAHAH! You made the right choice, not helping those nasssty humansss!" . "TODO")
("The goblins finish off the town, and share 1000@ of scrap with you." . "TODO")
("Assist humans." . "TODO")
("Do nothing." . "TODO")
)