'(("You come upon the scene of a heated battle. <B:0> A goblin resource harvester vessel is attacking an unarmed village, its beams slicing through the town. <B:0> Noticing you, the goblins briefly stop attacking…" . "TODO")
("<c:Goblin:2>You think you can fight usss?! Hah!!" . "TODO")
("One of the villagers came aboard to help out!" . "TODO")
("The goblins resume their attack. <B:0> " . "TODO")
("Maybe you weren't strong enough to face them anyway…" . "TODO")
("<c:Villager:5>That goblin harvester is slicing chunks off of our town! They just let the scrap fall to the ruined world below, where their friends collect the fallen resources. Anyway, can you help??" . "TODO")
("Sorry, but no." . "TODO")
("<c:Villager:5>Oh! Just in time! Can you help us!? That goblin ship over there is very strong, but there's a chance you could defeat them..." . "TODO")
("Of course!" . "TODO")
("What's going on here?" . "TODO")
("Sorry, I can't help." . "TODO")
)