'(("A nearby island seems to be transmitting an unusual distress signal..." . "TODO")
("Upon closer inspection, you find that the castle may contain valuable cargo, but it's overgrown with mycelium. You can explore, although there's some risk of cross-contamination. Board anyway?" . "TODO")
("Let's explore!" . "TODO")
("No way!" . "TODO")
("What's mycelium?" . "TODO")
("Mycelium is a substance that started infesting islands recently. It's pretty difficult to contain; some ships have a policy of burning infested islands on sight. Mycelium grows over the whole surface of an island, sucking a bit more power each time it grows larger. But it does have some defensive potential; when carefully contained, it can be useful as hull. <B:0> Anyway, should we board?" . "TODO")
("One of your crewmembers finds a data cartridge tangled in the fungal roots..." . "TODO")
("While attempting to board, several spores on the castle burst, infesting your island with mycelium!" . "TODO")
("You explore, and find cargo worth %@!" . "TODO")
)