'(("<b:/scripts/data/img/docks.img.bin>While docking at a crowded transit hub, you notice a dog wandering between the platforms..." . "TODO")
("<c:Station Master:9>Poor thing's owner had to evacuate ahead of the storm. Been trying to find someone to take him in before we have to close the station..." . "TODO")
("He seems friendly, invite him aboard?" . "TODO")
("<c:Dog:24>BOWOWOWOW!" . "TODO")
("Place block (1x2):" . "TODO")
("<c:Dog:24>Woof! Bowowow!" . "TODO")
("A new friend joins your crew!" . "TODO")
("<c:Station Master:9>Not much of a mechanic, but quick on his feet and fierce in a fight!" . "TODO")
)