'(("You come across an explorer's balloon, floating gently in the breeze. You adjust your engines to keep pace with it..." . "TODO")
("<c:Explorer:22>Hey there! You know, looks like we're going in the same direction! How about we join up?" . "TODO")
("He seems harmless, invite him aboard?" . "TODO")
("Welcome aboard!" . "TODO")
("Sorry, but no." . "TODO")
("Let's chat…" . "TODO")
("<c:Explorer:22>I'm obsessed with finding new islands! When I find one, I mark it with a signal beacon. That's how you can find islands on your sky chart! Neat huh? <B:0> Anyway, can I come aboard?" . "TODO")
("The explorer joined your crew. Hungry, he ate 600@ of your food supplies!" . "TODO")
("Sadly, there's no room..." . "TODO")
("<c:Explorer:22>No room in your castle? Hold on, I've got some supplies, I'll help out..." . "TODO")
("Place ladder (1x2):" . "TODO")
("<c:explorer:22>Thanks! I'll try to help out however I can!" . "TODO")
("The explorer joined your crew!" . "TODO")
)