'(("You encounter a Sylph civilian vessel. The occupant is fleeing..." . "TODO")
("<c:Sylph Artisan:46>They're calling everyone to military service. Everyone! <B:0> I'm a crystal sculptor. I know nothing of weapons. But the Conclave says 'all resources must be optimized for defense.' <B:0> They're converting our workshops into armories. Our archives into barracks. <B:0> I... I couldn't do it. I left." . "TODO")
("He seems harmless, invite him aboard?" . "TODO")
("Join up with us!" . "TODO")
("Best of luck…" . "TODO")
("Why leave now?" . "TODO")
("<c:Sylph Artisan:46>Three days ago, they ordered me to disassemble the Hall of Echoes, a resonance chamber that took my mentor forty years to tune. <B:0> 'Salvage the crystals for weapon cores,' they said. <B:0> I asked if we were at least recording the acoustic patterns, preserving the knowledge. <B:0> The overseer told me: 'We can rebuild archives after we survive. We cannot rebuild if we are dead.' <B:0> [pause] <B:0> But what survives if we destroy everything that made us worth saving?" . "TODO")
("The deserter joined your crew. Hungry, he ate 600@ of your food supplies!" . "TODO")
("Sadly, there's no room..." . "TODO")
("<c:Sylph Artisan:46>No room in your castle? Hold on, I've got some supplies, I'll help out..." . "TODO")
("Place ladder (1x2):" . "TODO")
("<c:Sylph Artisan:46>Thanks! I'll try to help out however I can!" . "TODO")
("The deserter joined your crew!" . "TODO")
)