'(("You spot strange flares arcing between the clouds... <B:0> A lone goblin perches atop a makeshift balloon, studying the patterns of island movements!" . "TODO")
("<c:Spotter:45>Sssaw your ship from my watching post! Been tracking island pathsss, marking which ones are ripe for raiding. Know all the bessst hunting groundsss!" . "TODO")
("He seems harmless, invite him aboard?" . "TODO")
("Welcome aboard!" . "TODO")
("Sorry, but no." . "TODO")
("Let's chat…" . "TODO")
("<c:Spotter:45>When rich islandsss passs overhead, I track their movement patterns. Could show you where the fat merchantsss like to hide... <B:0> Need a ssspotter on your crew?" . "TODO")
("Explain your goggles?" . "TODO")
("<c:Spotter:45>Ohhh! These ssspecial goggles are necesssary! <B:0> It's so bright when staring out at the cloudsss, without this visor, I'd go sssun-blind! <B:0> Anyway, I've got lotsss of experience, need a ssspotter?" . "TODO")
("The spotter joined your crew. Hungry, he ate 600@ of your food supplies!" . "TODO")
("Sadly, there's no room..." . "TODO")
("<c:Spotter:45>No room in your castle? Hold on, I've got some supplies, I'll help out..." . "TODO")
("Place ladder (1x2):" . "TODO")
("<c:Spotter:45>Thanks! I'll try to help out however I can!" . "TODO")
("The spotter joined your crew!" . "TODO")
)