'(("<c:Milo:5>Hi again, we're just getting prepared for a fight! We've built a pretty strong castle, and I think we can easily win. Let's start by setting up our weapons, as usual:" . "TODO")
("<c:Milo:5>In fact, I'm so sure we can win, that I don't want to sit around waiting forever for this fight to finish. Did you know you can speed up or slow down the battle? When tapped, the L button pauses the game. But when held, the L button lets you pick a number of different game speeds. Let's set the game speed to fast mode!" . "TODO")
("<c:Milo:5>Err... maybe this isn't going as well as I planned..." . "TODO")
("<c:Milo:5>I think we need to slow things down and take a closer look at what's going on. I have an idea... I'll set the game speed to the slow setting!" . "TODO")
("<c:Milo:5>OK, I've let this go on too long... I hate admitting my mistakes, but I've messed up everything! But guess what? You can rewind the battle too! Let's go all the way back to the beginning!" . "TODO")
("<c:Milo:5>Alright, I think I've showed you all the different game speeds: slow, regular, fast, paused, and rewind!" . "TODO")
)