'(("<c:Milo:5>So beautiful up here above the clouds! But look, just out there, pirates!" . "TODO")
("<c:Milo:5>And look at our castle! Defenseless! They really caught us off guard. Let's pause things with the L button, and size up the situation!" . "TODO")
("<c:Milo:5>Looks like our opponent has a weapon, one missile silo! We should build some defenses!" . "TODO")
("<c:Milo:5>The R button opens the construction menu, where you can build all sorts of stuff. At the bottom of the screen, you'll see the name and cost of each structure. In the top left, you'll see your current resource count and power usage! <d:1000> Err... <d:1000> they've got missiles, so I guess we should build some hull." . "TODO")
("<c:Milo:5>Looks like we took some damage. You can see the health of a block by hovering over it with your cursor." . "TODO")
("<c:Milo:5>We should fight back, let's build some weapons of our own!" . "TODO")
("<c:Milo:5>Navigate to a weapon, and press A to open the target selection menu." . "TODO")
("<c:Milo:5>Those blasted pirates! They've opened up a hole in our hull! We should probably fix that!" . "TODO")
("<c:Milo:5>Well, that covers the basics of construction and combat! As your castle grows, you'll want to build a workshop, to enable you to build new weapons, shields, and power supplies. If you ever need help with anything else, I'll be in a room labeled 'extras', you know, to the right of the room labelled 'challenges'. Just press the 'Tutorials' button to get my attention!" . "TODO")
)