'(("Introduction" . "TODO")
("Game Speed" . "TODO")
("Weapon Groups" . "TODO")
("Firing Patterns" . "TODO")
("Target Queueing" . "TODO")
("Salvage" . "TODO")
("Moving Blocks" . "TODO")
("Construction Tricks" . "TODO")
("Advanced Structures" . "TODO")
("Your Crew" . "TODO")
("Replicators" . "TODO")
("Transporters" . "TODO")
("Portals" . "TODO")
("Adding Terrain" . "TODO")
("Power Balance" . "TODO")
("Diverting Power" . "TODO")
)